### PR TITLE
fixed typo, from 'types' -> 'type'

### LINKED ISSUE #1: Breaks on latest Nim version
Using Nim `0.19` complains about the pure `Enum` on Line 32 ?.

Possibly remove the Enum ?, use an string?.

`$ nim doc xdo.nim `

```nim
xdo.nim(32, 3) Error: invalid indentation
xdo.nim(32, 10) Warning: Number of spaces around '*' is not consistent [Spacing]
xdo.nim(32, 20) Error: expression expected, but found '='
xdo.nim(33, 5) Error: invalid indentation
xdo.nim(34, 5) Error: invalid indentation
xdo.nim(35, 5) Error: invalid indentation
xdo.nim(36, 5) Error: invalid indentation
xdo.nim(37, 5) Error: invalid indentation
xdo.nim(38, 5) Error: invalid indentation
xdo.nim(39, 5) Error: invalid indentation
xdo.nim(40, 5) Error: invalid indentation
xdo.nim(41, 5) Error: invalid indentation
xdo.nim(42, 5) Error: invalid indentation
xdo.nim(43, 5) Error: invalid indentation
xdo.nim(44, 5) Error: invalid indentation
xdo.nim(45, 5) Error: invalid indentation
xdo.nim(46, 5) Error: invalid indentation
xdo.nim(47, 5) Error: invalid indentation
xdo.nim(48, 5) Error: invalid indentation
xdo.nim(49, 5) Error: invalid indentation
xdo.nim(50, 5) Error: invalid indentation
xdo.nim(31, 1) Error: undeclared identifier: 'types'
xdo.nim(32, 3) Error: undeclared identifier: 'Actions'
???(0, 0) Error: in expression ' enum': identifier expected, but found ''
xdo.nim(32, 22) Error: attempting to call undeclared routine: '<Error>'
???(0, 0) Error: in expression ' enum': identifier expected, but found ''
xdo.nim(32, 22) Error: attempting to call undeclared routine: '<Error>'
xdo.nim(32, 22) Error: expression '' cannot be called
xdo.nim(32, 10) Error: expression 'Actions *' is of type 'int32' and has to be discarded
xdo.nim(33, 5) Error: 'close' cannot be assigned to
xdo.nim(34, 5) Error: 'kill' cannot be assigned to
xdo.nim(35, 5) Error: undeclared identifier: 'hide'
xdo.nim(35, 5) Error: 'hide' cannot be assigned to
xdo.nim(36, 5) Error: undeclared identifier: 'show'
xdo.nim(36, 5) Error: 'show' cannot be assigned to
xdo.nim(37, 5) Error: undeclared identifier: 'raize'
xdo.nim(37, 5) Error: 'raize' cannot be assigned to
xdo.nim(38, 5) Error: undeclared identifier: 'lower'
xdo.nim(38, 5) Error: 'lower' cannot be assigned to
xdo.nim(39, 5) Error: undeclared identifier: 'below'
xdo.nim(39, 5) Error: 'below' cannot be assigned to
xdo.nim(40, 5) Error: undeclared identifier: 'above'
xdo.nim(40, 5) Error: 'above' cannot be assigned to
xdo.nim(41, 5) Error: 'move' cannot be assigned to
xdo.nim(42, 5) Error: 'resize' cannot be assigned to
xdo.nim(43, 5) Error: undeclared identifier: 'activate'
xdo.nim(43, 5) Error: 'activate' cannot be assigned to
xdo.nim(44, 5) Error: undeclared identifier: 'id'
xdo.nim(44, 5) Error: 'id' cannot be assigned to
xdo.nim(45, 5) Error: undeclared identifier: 'pid'
xdo.nim(45, 5) Error: 'pid' cannot be assigned to
xdo.nim(46, 5) Error: undeclared identifier: 'key_press'
xdo.nim(46, 5) Error: 'key_press' cannot be assigned to
xdo.nim(47, 5) Error: undeclared identifier: 'key_release'
xdo.nim(47, 5) Error: 'key_release' cannot be assigned to
xdo.nim(48, 5) Error: undeclared identifier: 'button_press'
xdo.nim(48, 5) Error: 'button_press' cannot be assigned to
xdo.nim(49, 5) Error: undeclared identifier: 'button_release'
xdo.nim(49, 5) Error: 'button_release' cannot be assigned to
xdo.nim(50, 5) Error: undeclared identifier: 'pointer_motion'
xdo.nim(50, 5) Error: 'pointer_motion' cannot be assigned to
```
:cat:

### PR DESCRIPTION
**Pull request by tzekid**
Hope this fixes #1 

I now get some other kind of error:

```
➜ nim doc src/xdo.nim
#... hints and all that ... then the prog runs
0.5.7
0x04800001
15311
(output: "", exitCode: 0)
(output: "", exitCode: 0)
(output: "", exitCode: 0)
(output: "", exitCode: 139)
(output: "", exitCode: 0)
(output: "", exitCode: 139)
(output: "", exitCode: 0)
(output: "", exitCode: 0)
 ^[[17~^[[H^[OR50^[OR^[[20~^[[18~^[OQxdo_examples1.nim(22)    xdo_examples1
xdo.nim(544)             xdo_type_current_dir
xdo.nim(533)             xdo_type
tables.nim(151)          []
Error: unhandled exception: key not found: P [KeyError]
Error: execution of an external program failed: '/home/tzekid/.cache/nim/xdo_d/runnableExamples/xdo_examples1 '
[Examples] failed: see /home/tzekid/.cache/nim/xdo_d/runnableExamples/xdo_examples1.nim
```

Time to create some xdo examples then? :smile:

### CODE REVIEW

File: src/xdo.nim [hunk 1]
```diff
@@ -28,7 +28,7 @@ const
     "191":"/","192":"`","219":"[","220":"\\","221":"]","222":"'"
   }.toTable  ## Statically compiled JSON that maps KeyCodes integers Versus Keys strings.
 
-types
+type
```
Comment (juancarlospaco) [inline src/xdo.nim:31]: Oh, wow, good catch, I introduced the error, I tracked it back to https://github.com/juancarlospaco/nim-xdo/commit/70872926be831dff32774d6bfa9db8d6be7bdaea#diff-8b7305597ed7f7ceb1592ac2ee2df68d

I dont take too much time on it because pure Enum are deprecated anyways.

**Comment by juancarlospaco** [comment]
Thanks!, is an awesome work.

I want to add `runnableExample`

If you are using this for something serious let me know, I can add u as contributor.

**Comment by tzekid** [comment]
Happy to Help! I simply stumbled upon this by chance. I could see myself creating some 'household' scripts to make my life easier with this though ...

Are _you_ using it for anything serious ?
